// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_4_1_long()
{
	NumpyEigenConverter<Eigen::Matrix< boost::int64_t, 4, 1 > >::register_converter();
}

