// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_5_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 2 > >::register_converter();
}

