SET(AUTOGEN_FILES
	src/autogen_module/numpy_eigen_export_module.cpp
	src/autogen_module/import_1_1_int.cpp
	src/autogen_module/import_1_1_float.cpp
	src/autogen_module/import_1_1_double.cpp
	src/autogen_module/import_1_1_uchar.cpp
	src/autogen_module/import_1_1_long.cpp
	src/autogen_module/import_1_2_int.cpp
	src/autogen_module/import_1_2_float.cpp
	src/autogen_module/import_1_2_double.cpp
	src/autogen_module/import_1_2_uchar.cpp
	src/autogen_module/import_1_2_long.cpp
	src/autogen_module/import_1_3_int.cpp
	src/autogen_module/import_1_3_float.cpp
	src/autogen_module/import_1_3_double.cpp
	src/autogen_module/import_1_3_uchar.cpp
	src/autogen_module/import_1_3_long.cpp
	src/autogen_module/import_1_4_int.cpp
	src/autogen_module/import_1_4_float.cpp
	src/autogen_module/import_1_4_double.cpp
	src/autogen_module/import_1_4_uchar.cpp
	src/autogen_module/import_1_4_long.cpp
	src/autogen_module/import_1_5_int.cpp
	src/autogen_module/import_1_5_float.cpp
	src/autogen_module/import_1_5_double.cpp
	src/autogen_module/import_1_5_uchar.cpp
	src/autogen_module/import_1_5_long.cpp
	src/autogen_module/import_1_6_int.cpp
	src/autogen_module/import_1_6_float.cpp
	src/autogen_module/import_1_6_double.cpp
	src/autogen_module/import_1_6_uchar.cpp
	src/autogen_module/import_1_6_long.cpp
	src/autogen_module/import_1_D_int.cpp
	src/autogen_module/import_1_D_float.cpp
	src/autogen_module/import_1_D_double.cpp
	src/autogen_module/import_1_D_uchar.cpp
	src/autogen_module/import_1_D_long.cpp
	src/autogen_module/import_2_1_int.cpp
	src/autogen_module/import_2_1_float.cpp
	src/autogen_module/import_2_1_double.cpp
	src/autogen_module/import_2_1_uchar.cpp
	src/autogen_module/import_2_1_long.cpp
	src/autogen_module/import_2_2_int.cpp
	src/autogen_module/import_2_2_float.cpp
	src/autogen_module/import_2_2_double.cpp
	src/autogen_module/import_2_2_uchar.cpp
	src/autogen_module/import_2_2_long.cpp
	src/autogen_module/import_2_3_int.cpp
	src/autogen_module/import_2_3_float.cpp
	src/autogen_module/import_2_3_double.cpp
	src/autogen_module/import_2_3_uchar.cpp
	src/autogen_module/import_2_3_long.cpp
	src/autogen_module/import_2_4_int.cpp
	src/autogen_module/import_2_4_float.cpp
	src/autogen_module/import_2_4_double.cpp
	src/autogen_module/import_2_4_uchar.cpp
	src/autogen_module/import_2_4_long.cpp
	src/autogen_module/import_2_5_int.cpp
	src/autogen_module/import_2_5_float.cpp
	src/autogen_module/import_2_5_double.cpp
	src/autogen_module/import_2_5_uchar.cpp
	src/autogen_module/import_2_5_long.cpp
	src/autogen_module/import_2_6_int.cpp
	src/autogen_module/import_2_6_float.cpp
	src/autogen_module/import_2_6_double.cpp
	src/autogen_module/import_2_6_uchar.cpp
	src/autogen_module/import_2_6_long.cpp
	src/autogen_module/import_2_D_int.cpp
	src/autogen_module/import_2_D_float.cpp
	src/autogen_module/import_2_D_double.cpp
	src/autogen_module/import_2_D_uchar.cpp
	src/autogen_module/import_2_D_long.cpp
	src/autogen_module/import_3_1_int.cpp
	src/autogen_module/import_3_1_float.cpp
	src/autogen_module/import_3_1_double.cpp
	src/autogen_module/import_3_1_uchar.cpp
	src/autogen_module/import_3_1_long.cpp
	src/autogen_module/import_3_2_int.cpp
	src/autogen_module/import_3_2_float.cpp
	src/autogen_module/import_3_2_double.cpp
	src/autogen_module/import_3_2_uchar.cpp
	src/autogen_module/import_3_2_long.cpp
	src/autogen_module/import_3_3_int.cpp
	src/autogen_module/import_3_3_float.cpp
	src/autogen_module/import_3_3_double.cpp
	src/autogen_module/import_3_3_uchar.cpp
	src/autogen_module/import_3_3_long.cpp
	src/autogen_module/import_3_4_int.cpp
	src/autogen_module/import_3_4_float.cpp
	src/autogen_module/import_3_4_double.cpp
	src/autogen_module/import_3_4_uchar.cpp
	src/autogen_module/import_3_4_long.cpp
	src/autogen_module/import_3_5_int.cpp
	src/autogen_module/import_3_5_float.cpp
	src/autogen_module/import_3_5_double.cpp
	src/autogen_module/import_3_5_uchar.cpp
	src/autogen_module/import_3_5_long.cpp
	src/autogen_module/import_3_6_int.cpp
	src/autogen_module/import_3_6_float.cpp
	src/autogen_module/import_3_6_double.cpp
	src/autogen_module/import_3_6_uchar.cpp
	src/autogen_module/import_3_6_long.cpp
	src/autogen_module/import_3_D_int.cpp
	src/autogen_module/import_3_D_float.cpp
	src/autogen_module/import_3_D_double.cpp
	src/autogen_module/import_3_D_uchar.cpp
	src/autogen_module/import_3_D_long.cpp
	src/autogen_module/import_4_1_int.cpp
	src/autogen_module/import_4_1_float.cpp
	src/autogen_module/import_4_1_double.cpp
	src/autogen_module/import_4_1_uchar.cpp
	src/autogen_module/import_4_1_long.cpp
	src/autogen_module/import_4_2_int.cpp
	src/autogen_module/import_4_2_float.cpp
	src/autogen_module/import_4_2_double.cpp
	src/autogen_module/import_4_2_uchar.cpp
	src/autogen_module/import_4_2_long.cpp
	src/autogen_module/import_4_3_int.cpp
	src/autogen_module/import_4_3_float.cpp
	src/autogen_module/import_4_3_double.cpp
	src/autogen_module/import_4_3_uchar.cpp
	src/autogen_module/import_4_3_long.cpp
	src/autogen_module/import_4_4_int.cpp
	src/autogen_module/import_4_4_float.cpp
	src/autogen_module/import_4_4_double.cpp
	src/autogen_module/import_4_4_uchar.cpp
	src/autogen_module/import_4_4_long.cpp
	src/autogen_module/import_4_5_int.cpp
	src/autogen_module/import_4_5_float.cpp
	src/autogen_module/import_4_5_double.cpp
	src/autogen_module/import_4_5_uchar.cpp
	src/autogen_module/import_4_5_long.cpp
	src/autogen_module/import_4_6_int.cpp
	src/autogen_module/import_4_6_float.cpp
	src/autogen_module/import_4_6_double.cpp
	src/autogen_module/import_4_6_uchar.cpp
	src/autogen_module/import_4_6_long.cpp
	src/autogen_module/import_4_D_int.cpp
	src/autogen_module/import_4_D_float.cpp
	src/autogen_module/import_4_D_double.cpp
	src/autogen_module/import_4_D_uchar.cpp
	src/autogen_module/import_4_D_long.cpp
	src/autogen_module/import_5_1_int.cpp
	src/autogen_module/import_5_1_float.cpp
	src/autogen_module/import_5_1_double.cpp
	src/autogen_module/import_5_1_uchar.cpp
	src/autogen_module/import_5_1_long.cpp
	src/autogen_module/import_5_2_int.cpp
	src/autogen_module/import_5_2_float.cpp
	src/autogen_module/import_5_2_double.cpp
	src/autogen_module/import_5_2_uchar.cpp
	src/autogen_module/import_5_2_long.cpp
	src/autogen_module/import_5_3_int.cpp
	src/autogen_module/import_5_3_float.cpp
	src/autogen_module/import_5_3_double.cpp
	src/autogen_module/import_5_3_uchar.cpp
	src/autogen_module/import_5_3_long.cpp
	src/autogen_module/import_5_4_int.cpp
	src/autogen_module/import_5_4_float.cpp
	src/autogen_module/import_5_4_double.cpp
	src/autogen_module/import_5_4_uchar.cpp
	src/autogen_module/import_5_4_long.cpp
	src/autogen_module/import_5_5_int.cpp
	src/autogen_module/import_5_5_float.cpp
	src/autogen_module/import_5_5_double.cpp
	src/autogen_module/import_5_5_uchar.cpp
	src/autogen_module/import_5_5_long.cpp
	src/autogen_module/import_5_6_int.cpp
	src/autogen_module/import_5_6_float.cpp
	src/autogen_module/import_5_6_double.cpp
	src/autogen_module/import_5_6_uchar.cpp
	src/autogen_module/import_5_6_long.cpp
	src/autogen_module/import_5_D_int.cpp
	src/autogen_module/import_5_D_float.cpp
	src/autogen_module/import_5_D_double.cpp
	src/autogen_module/import_5_D_uchar.cpp
	src/autogen_module/import_5_D_long.cpp
	src/autogen_module/import_6_1_int.cpp
	src/autogen_module/import_6_1_float.cpp
	src/autogen_module/import_6_1_double.cpp
	src/autogen_module/import_6_1_uchar.cpp
	src/autogen_module/import_6_1_long.cpp
	src/autogen_module/import_6_2_int.cpp
	src/autogen_module/import_6_2_float.cpp
	src/autogen_module/import_6_2_double.cpp
	src/autogen_module/import_6_2_uchar.cpp
	src/autogen_module/import_6_2_long.cpp
	src/autogen_module/import_6_3_int.cpp
	src/autogen_module/import_6_3_float.cpp
	src/autogen_module/import_6_3_double.cpp
	src/autogen_module/import_6_3_uchar.cpp
	src/autogen_module/import_6_3_long.cpp
	src/autogen_module/import_6_4_int.cpp
	src/autogen_module/import_6_4_float.cpp
	src/autogen_module/import_6_4_double.cpp
	src/autogen_module/import_6_4_uchar.cpp
	src/autogen_module/import_6_4_long.cpp
	src/autogen_module/import_6_5_int.cpp
	src/autogen_module/import_6_5_float.cpp
	src/autogen_module/import_6_5_double.cpp
	src/autogen_module/import_6_5_uchar.cpp
	src/autogen_module/import_6_5_long.cpp
	src/autogen_module/import_6_6_int.cpp
	src/autogen_module/import_6_6_float.cpp
	src/autogen_module/import_6_6_double.cpp
	src/autogen_module/import_6_6_uchar.cpp
	src/autogen_module/import_6_6_long.cpp
	src/autogen_module/import_6_D_int.cpp
	src/autogen_module/import_6_D_float.cpp
	src/autogen_module/import_6_D_double.cpp
	src/autogen_module/import_6_D_uchar.cpp
	src/autogen_module/import_6_D_long.cpp
	src/autogen_module/import_D_1_int.cpp
	src/autogen_module/import_D_1_float.cpp
	src/autogen_module/import_D_1_double.cpp
	src/autogen_module/import_D_1_uchar.cpp
	src/autogen_module/import_D_1_long.cpp
	src/autogen_module/import_D_2_int.cpp
	src/autogen_module/import_D_2_float.cpp
	src/autogen_module/import_D_2_double.cpp
	src/autogen_module/import_D_2_uchar.cpp
	src/autogen_module/import_D_2_long.cpp
	src/autogen_module/import_D_3_int.cpp
	src/autogen_module/import_D_3_float.cpp
	src/autogen_module/import_D_3_double.cpp
	src/autogen_module/import_D_3_uchar.cpp
	src/autogen_module/import_D_3_long.cpp
	src/autogen_module/import_D_4_int.cpp
	src/autogen_module/import_D_4_float.cpp
	src/autogen_module/import_D_4_double.cpp
	src/autogen_module/import_D_4_uchar.cpp
	src/autogen_module/import_D_4_long.cpp
	src/autogen_module/import_D_5_int.cpp
	src/autogen_module/import_D_5_float.cpp
	src/autogen_module/import_D_5_double.cpp
	src/autogen_module/import_D_5_uchar.cpp
	src/autogen_module/import_D_5_long.cpp
	src/autogen_module/import_D_6_int.cpp
	src/autogen_module/import_D_6_float.cpp
	src/autogen_module/import_D_6_double.cpp
	src/autogen_module/import_D_6_uchar.cpp
	src/autogen_module/import_D_6_long.cpp
	src/autogen_module/import_D_D_int.cpp
	src/autogen_module/import_D_D_float.cpp
	src/autogen_module/import_D_D_double.cpp
	src/autogen_module/import_D_D_uchar.cpp
	src/autogen_module/import_D_D_long.cpp
)
