#!/usr/bin/env python
import argparse
import kalibr_common as kc
from mpl_toolkits.mplot3d import art3d, Axes3D, proj3d
import numpy as np
import pylab as pl
import sm


def parseArguments():
    parser = argparse.ArgumentParser(
        description='Visualizes a camchain.yaml or camchain-imu.yaml file.')
    parser.add_argument(
        '--cam',
        dest='chainYaml',
        help='Camera configuration as yaml file.',
        nargs='+',
        required=True)
    parser.add_argument(
        '--azim',
        dest='azimView',
        help='Azimuth angle of the view.',
        type=float,
        default=90,
        required=False)
    parser.add_argument(
        '--elev',
        dest='elevView',
        help='Elevation angle of the view.',
        type=float,
        default=0,
        required=False)
    parsed_args = parser.parse_args()
    return parsed_args


def axisEqual3D(ax):
    extents = np.array(
        [getattr(ax, 'get_{}lim'.format(dim))() for dim in 'xyz'])
    sz = extents[:, 1] - extents[:, 0]
    centers = np.mean(extents, axis=1)
    maxsize = max(abs(sz))
    r = maxsize / 2
    for ctr, dim in zip(centers, 'xyz'):
        getattr(ax, 'set_{}lim'.format(dim))(ctr - r, ctr + r)
    ax.set_aspect('equal')


def orthogonalProjection(zfront, zback):
    a = (zfront + zback) / (zfront - zback)
    b = -2 * (zfront * zback) / (zfront - zback)
    return np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, a, b],
                     [0, 0, -0.00001, zback]])


def transformPointcloud(transform, points):
    assert points.shape[1] == 3
    points_transformed = points.copy()
    for index in range(points.shape[0]):
        point_transformed = transform * points[index, :].reshape(3, 1)
        points_transformed[index, :] = point_transformed.reshape(1, 3)
    return points_transformed


class CalibrationVisualization:

    def __init__(self):
        self.color_counter = 0
        self.fig = pl.figure()
        self.ax = self.fig.gca(projection='3d')
        self.color_list = pl.cm.Pastel1(np.linspace(0, 1, 12))

    def addCameraPlot(self, transform, intrinsics, resolution):
        focal_lengths = intrinsics[0:2]
        principal_point = intrinsics[2:4]
        self.__drawCameraOutline(transform, focal_lengths, principal_point,
                                 resolution)

    def showPlot(self, azim, elev):
        self.ax.view_init(azim=azim, elev=elev)
        proj3d.persp_transformation = orthogonalProjection
        axisEqual3D(self.ax)
        pl.show()

    def incrementColor(self):
        self.color_counter = self.color_counter + 1

    def __drawCameraOutline(self, transform, focal_lengths, principal_point,
                            resolution):
        scaling_factor = 1e-4
        pixel_ratio = focal_lengths[0] / focal_lengths[1]
        scaled_focal_length = scaling_factor * focal_lengths[0]
        x_range = scaling_factor * np.array(
            [-principal_point[0], resolution[0] - principal_point[0]])
        y_range = pixel_ratio * scaling_factor * np.array(
            [-principal_point[1], resolution[1] - principal_point[1]])
        raw_camera_corners = np.array(
            [[x_range[0], y_range[0], scaled_focal_length], [
                x_range[1], y_range[0], scaled_focal_length
            ], [x_range[1], y_range[1], scaled_focal_length],
             [x_range[0], y_range[1], scaled_focal_length], [0, 0, 0]])
        camera_corners = transformPointcloud(transform, raw_camera_corners)
        vertices = [[camera_corners[0], camera_corners[1], camera_corners[4]], [
            camera_corners[0], camera_corners[3], camera_corners[4]
        ], [camera_corners[2], camera_corners[1], camera_corners[4]],
                    [camera_corners[2], camera_corners[3], camera_corners[4]], [
                        camera_corners[0], camera_corners[1], camera_corners[2],
                        camera_corners[3]
                    ]]
        fill_color = self.color_list[self.color_counter % 12]
        # Focal point.
        self.ax.scatter3D(
            camera_corners[4, 0],
            camera_corners[4, 1],
            camera_corners[4, 2],
            c=fill_color,
            s=3e5 * scaling_factor)
        # Image plane corners.
        self.ax.scatter3D(
            camera_corners[1:4, 0],
            camera_corners[1:4, 1],
            camera_corners[1:4, 2],
            c=fill_color,
            s=1e5 * scaling_factor)
        # Planes of camera models.
        self.ax.add_collection3d(
            art3d.Poly3DCollection(
                vertices,
                facecolors=fill_color,
                linewidths=1,
                edgecolors='k',
                alpha=.5,
                antialiased=True))


def getDistance(point, other_point):
    difference_vector = other_point - point
    return np.linalg.norm(difference_vector)


def main():
    parsed_args = parseArguments()
    calibration_visualization = CalibrationVisualization()
    for camchain_yaml in parsed_args.chainYaml:
        camchain = kc.ConfigReader.CameraChainParameters(camchain_yaml)
        num_cameras = camchain.numCameras()
        print("Plotting configuration with " + str(num_cameras) + " cameras.")
        T_current = sm.Transformation()
        for cam_index in range(num_cameras):
            cam = 'cam{0}'.format(cam_index)
            if cam != 'cam0':
                T_current = T_current * camchain.getExtrinsicsLastCamToHere(
                    cam_index)
            intrinsics = np.asarray(camchain.data[cam]['intrinsics'])
            resolution = np.asarray(camchain.data[cam]['resolution'])
            calibration_visualization.addCameraPlot(T_current, intrinsics,
                                                    resolution)
        calibration_visualization.incrementColor()
    calibration_visualization.showPlot(parsed_args.azimView,
                                       parsed_args.elevView)


if __name__ == "__main__":
    main()
