# THIS FILE HAS BEEN AUTOGENERATED BY gen_files.py
SET( AUTOGEN_CAMERA_CPP_FILES
	src/autogen/Camera-PinholeCameraGeometry.cpp
	src/autogen/Camera-DistortedPinholeCameraGeometry.cpp
	src/autogen/Camera-EquidistantDistortedPinholeCameraGeometry.cpp
	src/autogen/Camera-OmniCameraGeometry.cpp
	src/autogen/Camera-DistortedOmniCameraGeometry.cpp
	src/autogen/Camera-EquidistantDistortedOmniCameraGeometry.cpp
#	src/autogen/Camera-PinholeRsCameraGeometry.cpp
#	src/autogen/Camera-DistortedPinholeRsCameraGeometry.cpp
#	src/autogen/Camera-EquidistantDistortedPinholeRsCameraGeometry.cpp
#	src/autogen/Camera-OmniRsCameraGeometry.cpp
#	src/autogen/Camera-DistortedOmniRsCameraGeometry.cpp
#	src/autogen/Camera-EquidistantDistortedOmniRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedPinholeCameraGeometry.cpp
#	src/autogen/Camera-MaskedDistortedPinholeCameraGeometry.cpp
#	src/autogen/Camera-MaskedEquidistantDistortedPinholeCameraGeometry.cpp
#	src/autogen/Camera-MaskedOmniCameraGeometry.cpp
#	src/autogen/Camera-MaskedDistortedOmniCameraGeometry.cpp
#	src/autogen/Camera-MaskedEquidistantDistortedOmniCameraGeometry.cpp
#	src/autogen/Camera-MaskedPinholeRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedDistortedPinholeRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedEquidistantDistortedPinholeRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedOmniRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedDistortedOmniRsCameraGeometry.cpp
#	src/autogen/Camera-MaskedEquidistantDistortedOmniRsCameraGeometry.cpp
#	src/autogen/Camera-DepthCameraGeometry.cpp
#	src/autogen/Camera-DistortedDepthCameraGeometry.cpp
#	src/autogen/Camera-EquidistantDistortedDepthCameraGeometry.cpp
)

