# THIS FILE HAS BEEN AUTOGENERATED BY gen_files.py
SET( AUTOGEN_FRAME_CPP_FILES
	src/autogen/Frame-PinholeCameraGeometry.cpp
	src/autogen/Frame-DistortedPinholeCameraGeometry.cpp
	src/autogen/Frame-EquidistantDistortedPinholeCameraGeometry.cpp
	src/autogen/Frame-OmniCameraGeometry.cpp
	src/autogen/Frame-DistortedOmniCameraGeometry.cpp
	src/autogen/Frame-EquidistantDistortedOmniCameraGeometry.cpp
	src/autogen/Frame-PinholeRsCameraGeometry.cpp
	src/autogen/Frame-DistortedPinholeRsCameraGeometry.cpp
	src/autogen/Frame-EquidistantDistortedPinholeRsCameraGeometry.cpp
	src/autogen/Frame-OmniRsCameraGeometry.cpp
	src/autogen/Frame-DistortedOmniRsCameraGeometry.cpp
	src/autogen/Frame-EquidistantDistortedOmniRsCameraGeometry.cpp
	src/autogen/Frame-MaskedPinholeCameraGeometry.cpp
	src/autogen/Frame-MaskedDistortedPinholeCameraGeometry.cpp
	src/autogen/Frame-MaskedEquidistantDistortedPinholeCameraGeometry.cpp
	src/autogen/Frame-MaskedOmniCameraGeometry.cpp
	src/autogen/Frame-MaskedDistortedOmniCameraGeometry.cpp
	src/autogen/Frame-MaskedEquidistantDistortedOmniCameraGeometry.cpp
	src/autogen/Frame-MaskedPinholeRsCameraGeometry.cpp
	src/autogen/Frame-MaskedDistortedPinholeRsCameraGeometry.cpp
	src/autogen/Frame-MaskedEquidistantDistortedPinholeRsCameraGeometry.cpp
	src/autogen/Frame-MaskedOmniRsCameraGeometry.cpp
	src/autogen/Frame-MaskedDistortedOmniRsCameraGeometry.cpp
	src/autogen/Frame-MaskedEquidistantDistortedOmniRsCameraGeometry.cpp
	src/autogen/Frame-DepthCameraGeometry.cpp
	src/autogen/Frame-DistortedDepthCameraGeometry.cpp
	src/autogen/Frame-EquidistantDistortedDepthCameraGeometry.cpp
)

