// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_6_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 6 > >::register_converter();
}

