// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_D_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 1 > >::register_converter();
}

