// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_3_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, Eigen::Dynamic > >::register_converter();
}

