// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_6_4_long()
{
	NumpyEigenConverter<Eigen::Matrix< boost::int64_t, 6, 4 > >::register_converter();
}

