// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_5_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, Eigen::Dynamic > >::register_converter();
}

