// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_1_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 3 > >::register_converter();
}

