// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_2_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 1 > >::register_converter();
}

