name: "Publish Ubuntu images"

on:
  release:
    types: [published]
  push:
    branches: [ feature/docker_push ]

jobs:
  push_to_registries:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        version: [16, 18, 20]
    name: Push Ubuntu ${{ matrix.version }}.04 Docker image
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_ros1_${{ matrix.version }}_04
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_HUB_REPOSITORY }}/kalibr:${{ matrix.version }}.04
